# application-prod.yml
server:
  port: ${SERVER_PORT:19100}

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
        maximum-pool-size: 5
        minimum-idle: 1
        idle-timeout: 30000
        max-lifetime: 1800000
        connection-timeout: 30000
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: user_service
        format_sql: true
    show-sql: true

  cloud:
    inetutils:
      ignored-interfaces:
        - "lo"
        - "docker.*"
        - "veth.*"
      preferred-networks:
        - "10.0"           # 본인 VPC CIDR 첫 두 옥텟
      use-only-site-local-interfaces: true

eureka:
  client:
    enabled: ${EUREKA_ENABLED:false}
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
